apiVersion: v1
kind: Service
metadata:
  labels:
    app: tyk-mongo
  name: mongo
  namespace: kube-tyk
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: tyk-mongo
