apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tyk-redis
  name: tyk-redis
  namespace: kube-tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tyk-redis
      name: tyk-redis
    spec:
      containers:
        - name: tyk-redis
          image: redis:3.2.5
          ports:
          - name: redis
            containerPort: 6379
            hostPort: 6379
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0:c123,c456"
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data/db
      volumes:
        - name: redis-persistent-storage
          gcePersistentDisk:
            pdName: gke-tyk-redis
            fsType: ext4