apiVersion: v1
kind: Service
metadata:
  labels:
    app: tyk-redis
  name: redis
  namespace: kube-tyk
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: tyk-redis
